language: cpp
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','boost-latest']
          packages: ['gcc-4.9','g++-4.9','ccache','libboost1.55-all-dev']
      env: COMPILERCXX=g++-4.9 COMPILERCC=gcc-4.9 TRAVIS_MEDUSA_BUILD_WITH_OGDF=FALSE
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','boost-latest']
          packages: ['g++-5','ccache','libboost1.55-all-dev']
      env: COMPILERCXX=g++-5 COMPILERCC=gcc-5 TRAVIS_MEDUSA_BUILD_WITH_OGDF=FALSE
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5','python-pygments','libxml2-utils','libpcre3','gdb','unzip','ccache']
      env: COMPILERCXX=g++-5 COMPILERCC=gcc-5 TRAVIS_CPPCAT=TRUE
      script: echo "no"
      before_install:
        - git clone https://github.com/danmar/cppcheck.git cppcheck
        - cd cppcheck
        - pwd
        - export CC="ccache $COMPILERCC"
        - export CXX="ccache $COMPILERCXX"
        - make
        - ls -la
      before_script:
        - cd ..
        - export PATH=$(pwd)/cppcheck:$PATH
        - pwd
        - cppcheck --version
        - cppcheck -q -j4 --enable=all  --template='{id} {file}:{line} {message}' --suppress=variableScope --platform=unix64 ./
cache:
- ccache
- apt

before_install:
  - git submodule update --init --recursive
  - cd .travis
  - wget --no-check-certificate -O cmake.tar.gz http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz
  - tar xzf cmake.tar.gz
  - ls -la
  - export PATH=$(pwd)/cmake-3.2.1-Linux-x86_64/bin:$PATH
  - cd ..

before_script:
  - mkdir build_release
  - cd build_release
  - export CC="ccache $COMPILERCC"
  - export CXX="ccache $COMPILERCXX"
  - ccache -s
  - cmake .. -DMEDUSA_BUILD_WITH_OGDF=$TRAVIS_MEDUSA_BUILD_WITH_OGDF -DCMAKE_BUILD_TYPE=Release
  - cd ..

script:
  - cd build_release
  - make all test
  - ccache -s
  - cd ..

notifications:
  irc: "chat.freenode.net#medusa_disasm"
