language: cpp
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','boost-latest']
          packages: ['gcc-4.9','g++-4.9','ccache','libboost1.55-all-dev']
      env: COMPILER=g++-4.9

cache:
- ccache
- apt

before_install:
  - git submodule update --init --recursive
  - export CC="ccache gcc-4.9"
  - export CXX="ccache g++-4.9"
  - cd .travis
  - wget --no-check-certificate -O cmake.tar.gz http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz
  - tar xvzf cmake.tar.gz
  - ls -la
  - export PATH=$(pwd)/cmake-3.2.1-Linux-x86_64/bin:$PATH
  - cd ..

before_script:
  - mkdir build_release
  - cd build_release
  - ccache -s
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cd ..

script:
  - cd build_release
  - make all test
  - ccache -s
  - cd ..

notifications:
  irc: "chat.freenode.net#medusa_disasm"
