version: 0.5.{build}
branches:
  only:
  - dev
  - appveyorfixcache
os: Unstable
configuration: Release
platform: x64
environment:
  BOOST_ROOT: C:\Libraries\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost\lib64-msvc-12.0
  QTDIR: C:\Qt\5.4\msvc2013_64_opengl
before_build:
- git submodule update --init --recursive
- md build
- cd build
- cmake -G"Visual Studio 12 Win64" ..
build:
  parallel: true                  # enable MSBuild parallel builds
  project: C:\projects\medusa\build\Medusa.sln
  verbosity: minimal
test_script:
- ctest -VV -C Release
